# Generated by Django 2.1 on 2018-09-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='HTML_Content',
            new_name='Content',
        ),
    ]
