# Generated by Django 2.1 on 2018-09-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180920_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Image',
            field=models.ImageField(default='/static/images/prof%20pic.jpg', upload_to=''),
        ),
    ]
