# Generated by Django 2.1 on 2018-09-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180920_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(default='Post Images/prof pic.jpg', upload_to='Post Images'),
        ),
    ]
