#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct  4 14:21:21 2018

@author: anishkhanna
"""

dict = {"a":1, "b":2}


if "a" in dict:
    dict["a"]+=3
list = list(dict.values())
print(list)